name: automated-testing-with-vitest
run-name: ${{ github.actor }} has started a job
on: [push]
jobs:
  automated-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm i
      - run: npm test
